Joxit/docker-registry-ui

- nginx/default.conf
Tested with nginx version `1.13.8` and  docker image `joxit/docker-registry-ui:static`
Useful to know: https://serverfault.com/a/644898
> Fix `REGISTRY_URL` not working

- nginx/default.conf
Hi,
Thank you very much for this wonderful image. Finally a good one who allows deleting images!
When pushing my images on my private registry, I met an error with nginx because the layer was about ~ 300 MB.
This fix intends to:
- Disable client_max_body_size to avoid the error '403 Request Entity Too Large' which prevent uploading "big" images.
- Apply recommended settings by Docker (https://docs.docker.com/registry/recipes/nginx)
> Fix '403 Request Entity Too Large'

- src/tags/app.tag
Close #45 
Sort on numbers when there are instead of characters.
> New tag sort using digits

- examples/ui-as-proxy/simple.yml
If I execute the following command, I get the error below. This PR fixes the issue.
```bash
docker-compose -f simple.yml up -d
```
>>>
WARNING: Some networks were defined but are not used by any service: registry-ui-net
ERROR: Service "registry" uses an undefined network "docker-registry-ui"
> fix docker network name

- src/style.css
- src/tags/remove-image.tag
- src/tags/taglist.tag
> [feat #29] Add multi select delete for tags

- bin/entrypoint
- examples/proxy-headers/README.md
- examples/proxy-headers/docker-compose.yml
- examples/proxy-headers/nginx.env
- examples/proxy-headers/registry-config/credentials.yml
- examples/proxy-headers/registry-config/htpasswd
- nginx/default.conf
- package.json
Headers can be useful in some cases such as avoid sending credentials when you are on the UI (like #87). Or give to the registry server other properties such as `X-Forward-For` or `Server` headers for monitoring.
This is compatible only with static version of the UI and used with `REGISTRY_URL` variable.
When you want to add a custom header, add to the registry ui a environment variable or entry in `/etc/nginx/.env` which looks like `NGINX_PROXY_HEADER_Custom_Header`. All underscores (`_`) will be replaced by hyphens (`-`). 
Some example of custom headers as variable:
- `NGINX_PROXY_HEADER_Authorization` for Basic auth credentials
- `NGINX_PROXY_HEADER_X_Forwarded_For` for identifying the originating IP address of a client
An example is bundled with this PR
Any feedback @marcusblake ? …
> Supports custom headers when the ui is used as proxy

- README.md
closes #97
closes #26 
closes #76
closes #77
> Add FAQ in Readme

- README.md
- bin/entrypoint
- src/scripts/script.js
- src/scripts/static.js
- src/tags/catalog.tag
> Add content element limit

- src/scripts/utils.js
- src/style.css
- src/tags/app.tag
- src/tags/tag-history-button.tag
- src/tags/tag-history.tag
This PR add the support for multi-arch images.
@bjj: This style is OK for you ?
closes #130
> Add tab for multi arch in history page

- arm32v7-static.dockerfile
- arm64v8-static.dockerfile
- bin/entrypoint
- debian-static.dockerfile
- static.dockerfile
Use the entrypoint mechanism available in the latest nginx images. This allows the user to execute custom scripts before the server starts.
I hope this doesn't break anything :)
> Use entrypoint mechanism from latest nginx images

- nginx/default.conf
Large images don't get correctly pushed to the docker registry when using an nginx reverse proxy with proxy_buffering enabled. What happens is pushing the image appears to succeed but when you pull the image, you eventually get an "unexpected EOF" error. Disabling proxy buffering resolves this issue. The images impacting me were about ~10GB.
FIx was found here. https://www.jfrog.com/jira/browse/RTFACT-16398?focusedCommentId=64722&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-64722
> Fixed unexpected EOF errors when pulling large images

- README.md
- bin/entrypoint
- examples/README.md
- examples/pr-219/README.md
- examples/pr-219/docker-compose.yml
- src/components/catalog/catalog.riot
- src/components/dialogs/add-registry-url.riot
- src/components/dialogs/change-registry-url.riot
- src/components/dialogs/dialogs-menu.riot
- src/components/dialogs/remove-registry-url.riot
- src/components/docker-registry-ui.riot
- src/index.html
- src/scripts/utils.js
Add support for default registries (options `DEFAULT_REGISTRIES`) you can add many registries separated with a comma.
Example:
`DEFAULT_REGISTRIES=https://registry.example.com,https://registry2.example.com,http://localhost:5000`
Add also read only registries (option `READ_ONLY_REGISTRIES`) that deactivate add and remove for registries.
These options works only when `SINGLE_REGISTRY=false`
Behaviors: 
- `DEFAULT_REGISTRIES`:
- will set the list of registries in the localstorage when the localstorage is empty.
- will overwrite the list of registries every time when  `READ_ONLY_REGISTRIES=true`
- `READ_ONLY_REGISTRIES`:
- will remove dialog for Add and Remove registries
resolves #211
> Multiple static registries

- CONTRIBUTORS.md
- Dockerfile
- README.md
- arm32v7.dockerfile
- arm64v8.dockerfile
- bin/entrypoint
- debian.dockerfile
With this PR you can run the container as the user `nginx` which do not have root access.
You can also run the server on a custom port with the environment variable  `NGINX_LISTEN_PORT`. Default values are `80` when the user is `root` and `8080` otherwise.
closes #224
> Add support for unprivileged user

- Dockerfile
- README.md
- arm32v7.dockerfile
- arm64v8.dockerfile
- bin/entrypoint
- debian.dockerfile
- src/components/catalog/catalog-element.riot
- src/components/catalog/catalog.riot
- src/components/docker-registry-ui.riot
- src/index.html
Add new option `SHOW_CATALOG_NB_TAGS`: Show number of tags per images on catalog page. This will produce + nb images requests, not recommended on large registries. Default value is `false`.
closes #161
> Show number of tags per image

- README.md
- bin/entrypoint
- src/components/docker-registry-ui.riot
- src/components/tag-history/tag-history-element.riot
- src/components/tag-history/tag-history.riot
- src/index.html
- src/scripts/utils.js
Add new option `HISTORY_CUSTOM_LABELS`, this will add a list of custom labels separated with coma 
Example: `HISTORY_CUSTOM_LABELS=my-first-label,my_second_label`
```Dockerfile
FROM joxit/docker-reigstry-ui
LABEL my-first-label="The Value of my-first-label"
LABEL my_second_label="The Value of my_second_label"
```
The UI will format your label and replace `_` and `-` with spaces.
closes #160
> Expose some custom labels

- README.md
- bin/90-docker-registry-ui.sh
- src/components/docker-registry-ui.riot
- src/components/tag-history/tag-history.riot
- src/components/tag-list/tag-list.riot
- src/index.html
- src/scripts/docker-image.js
I'm facing some issues with registry server cache control (see https://github.com/Joxit/docker-registry-ui/issues/260#issuecomment-1239543652)
The docker registry UI is built on top of the registry server API v2 and it implements some HTTP specs incorrectly. This time I'm talking about cache control and [ETag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag).
As I speak, when you are requesting a resource such as a tag manifest (e.g. `/v2/nginx/manifests/1.23`) and your browser cache control is activated, you will get a ETag in the response. When you use this ETag in `If-None-Match` header, you will receive 304 even if your headers and the body have changed.
```sh
curl -I 'http://127.0.0.1:5000/v2/nginx/manifests/1.23' -H 'Accept: …
```
> Add new option `ADD_NO_CACHE_HEADER` on requests to registry server

- src/components/dialogs/dockerfile.riot
- src/components/tag-history/tag-history.riot
This feature add a new button in history page to show the raw dockerfile (like Dockerhub)
closes #261
> Show dockerfile

- src/components/docker-registry-ui.riot
- src/components/tag-list/remove-image.riot
- src/components/tag-list/tag-table.riot
This PR adds a new feature: shift + click to select multiple tags in a row!
closes #258
> Add support to shift + click for multi delete in a row

- package.json
- src/components/docker-registry-ui.riot
- src/index.js
- src/scripts/theme.js
- src/style.scss
This feature add a switch to change the theme when it's in auto mode.
> Add switch to manually change theme from light to dark

- src/components/tag-list/tag-table.riot
E.g. OCI build-cache doesnt have a created date available, which leads to an error due to creationDate being undefined.
> Fix sorting of images w/o date.

- src/scripts/http.js
The docker spec for authentication using oauth2 refers to the key "access_token". Simple addition to support token responses containing access_token.
https://docs.docker.com/registry/spec/auth/oauth/
> support for the docker spec oauth2 token

- examples/token-auth-keycloak/conf/proxy/nginx.conf
You were missing CORS headers for regular access (you only added headers for OPTIONS and if not authorized but they are missing if you are authenticated. Chrome complains then with missing CORS headers)
> added missing CORS headers for regular keycloak access via AJAX

- README.md
- bin/90-docker-registry-ui.sh
- src/components/docker-registry-ui.riot
- src/components/tag-list/tag-list.riot
- src/components/tag-list/tag-table.riot
- src/index.html
> Tags per page

- nginx/default.conf
Support receiving bigger headers and big cookies (sometimes set when reverse proxy is doing some sort of auth)
> Avoid 400 - Too big request header when cookie is defined

- examples/read-only-auth/docker-compose.yml
Hi,
Thank you for this very useful project!
There's a small error in the naming of the authentication files in the read-only-auth example that makes it non-functional.
A very small PR to complete this one https://github.com/Joxit/docker-registry-ui/pull/371 
reproduction of the problem :
```
git clone https://github.com/Joxit/docker-registry-ui
cd docker-registry-ui/examples/read-only-auth/
docker compose up -d
sleep 1
curl 'http://localhost/v2/_catalog?n=1000' -H 'Authorization: Basic aW52YWxpZDppbnZhbGlkCg=='
```
current behavior :
```
Cloning into 'docker-registry-ui'...
remote: Enumerating objects: 4070, done.
remote: Counting objects: 100% (798/798), done.
remote: Compressing objects: 100% (283/283), done.
remote: Total 4070 (delta 552), reused 691 (delta 500), pack-reused 3272 (from …
```
> docs(examples): inconsistency of htpasswd file names with docker compose.yml (read-only-auth example)
